blank_issues_enabled: true
contact_links:
  - name: Sopel's IRC channel
    url: https://kiwiirc.com/client/irc.libera.chat/#sopel
    about: "For more interactive help, ask in #sopel on Libera Chat. We're usually there daily."
