name: 'Main CI Build'
on:
  push:
    branches:
      - master
      - Testing
  pull_request_target:

jobs:
  test:
    name: Test Build (Python ${{ matrix.python }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ['3.6', '3.7', '3.8', '3.8-dev', '3.9', '3.9-dev', '3.10-dev']
        os: ['ubuntu-latest', 'macos-latest']
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          submodules: false
      - name: Setup Python ${{ matrix.python }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pyproject-build --wheel --outdir dist .
          find dist -name "*.whl" | xargs pip3 install
      - name: Show python version and show package
        run: |
          python --version
          sopel --version
      - name: Run tests
        run: |
          make quality
          pip check
      - name: Run pip freeze and pipdeptree
        run: |
          pip freeze
          pipdeptree
      - name: Show outdated packages
        run: pip list --outdated
